export const UPDATE_ONLINE_USERS = 'UPDATE_ONLINE_USERS';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const GET_MESSAGE_HISTORY_REQUEST = 'GET_MESSAGE_HISTORY_REQUEST';
export const GET_MESSAGE_HISTORY_SUCCESS = 'GET_MESSAGE_HISTORY_SUCCESS';
export const GET_MESSAGE_HISTORY_FAILURE = 'GET_MESSAGE_HISTORY_FAILURE';

export const CLOSE_IMG_VIEWER = 'CLOSE_IMG_VIEWER';
export const OPEN_IMG_VIEWER = 'OPEN_IMG_VIEWER';

export const FETCH_OLDER_CHAT_HISTORY_REQUEST = 'FETCH_OLDER_CHAT_HISTORY_REQUEST';
export const FETCH_OLDER_CHAT_HISTORY_SUCCESS = 'FETCH_OLDER_CHAT_HISTORY_SUCCESS';
export const FETCH_OLDER_CHAT_HISTORY_FAILURE = 'FETCH_OLDER_CHAT_HISTORY_FAILURE';
