import {createConstants} from '../../utils';

export default createConstants(
	'USER_SIGNIN_REQUEST',
	'USER_SIGNIN_SUCCESS',
	'USER_SIGNIN_FAILURE',
	'USER_SIGNUP_SUCCESS',
	'USER_SIGNUP_FAILURE',
	'USER_SIGNOUT',
	'RECEIVE_PERSONAL_HOME_DATA',
	'FETCH_PERSONAL_HOME_DATA_REQUEST'
);