export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAILURE = 'ADD_TASK_FAILURE';

export const CHANGE_TASK_SUM_SUCCESS = 'CHANGE_TASK_SUM_SUCCESS';
export const CHANGE_TASK_SUM_FAILURE = 'CHANGE_TASK_SUM_FAILURE';

export const EDIT_TASK_REQUEST = 'EDIT_TASK_REQUEST';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_FAILURE = 'EDIT_TASK_FAILURE';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';

export const SET_CURRENT_TASKLIST = 'SET_CURRENT_TASKLIST';
export const NULL_TASKLIST_ID = 'NULL_TASKLIST_ID';

export const OPEN_USERS_DROPDOWN = 'OPEN_USERS_DROPDOWN';
export const CLOSE_USERS_DROPDOWN = 'CLOSE_USERS_DROPDOWN';

export const OPEN_TAGS_DROPDOWN = 'OPEN_TAGS_DROPDOWN';
export const CLOSE_TAGS_DROPDOWN = 'CLOSE_TAGS_DROPDOWN';

export const ADD_EXECUTOR = 'ADD_EXECUTOR';
export const REMOVE_EXECUTOR = 'REMOVE_EXECUTOR';
export const REMOVE_ALL_EXECUTOR = 'REMOVE_ALL_EXECUTOR';

export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const REMOVE_ALL_TAG = 'REMOVE_ALL_TAG';

export const TOGGLE_TASK_REQUEST = 'TOGGLE_TASK_REQUEST';
export const TOGGLE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS';
export const TOGGLE_TASK_FAILURE = 'TOGGLE_TASK_FAILURE';
export const ADD_ACCOMPLISHED_TASK_REQUEST = 'ADD_ACCOMPLISHED_TASK_REQUEST';
export const ADD_ACCOMPLISHED_TASK_SUCCESS = 'ADD_ACCOMPLISHED_TASK_SUCCESS';
export const ADD_ACCOMPLISHED_TASK_FAILURE = 'ADD_ACCOMPLISHED_TASK_FAILURE';

export const SHOW_TASK_DETAIL = 'SHOW_TASK_DETAIL';

export const INVALID_INPUT = 'INVALID_INPUT';
export const INVALID_INPUT_MAX_LENGTH = 'INVALID_INPUT_MAX_LENGTH';

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';

export const SET_SELECTED_PRIORITY = 'SET_SELECTED_PRIORITY';